[package]
name = "helios-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.5.1"
mpl-token-metadata = "4.1.2"
solana-client = "1.18.9"
solana-sdk = "1.18.9"
